.TH "PiP-API5-exit" 3 "Fri Jun 10 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiP-API5-exit \- API: termination and signaling
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBpip_exit\fP"
.br
.ti -1c
.RI "\fBpip_kill_all_child_tasks\fP"
.br
.ti -1c
.RI "\fBpip_abort\fP"
.br
.ti -1c
.RI "\fBpip_kill\fP"
.br
.ti -1c
.RI "\fBpip_sigmask\fP"
.br
.ti -1c
.RI "\fBpip_signal_wait\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
