.TH "PiP-API6-sync" 3 "Mon May 23 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiP-API6-sync \- API: Synchronization
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBpip_yield\fP"
.br
.ti -1c
.RI "\fBpip_barrier_init\fP"
.br
.ti -1c
.RI "\fBpip_barrier_wait\fP"
.br
.ti -1c
.RI "\fBpip_barrier_fin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
