.TH "PiP-API3-wait" 3 "Thu May 19 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiP-API3-wait \- API: Waiting for PiP task termination
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBpip_wait\fP"
.br
.ti -1c
.RI "\fBpip_trywait\fP"
.br
.ti -1c
.RI "\fBpip_wait_any\fP"
.br
.ti -1c
.RI "\fBpip_trywait_any\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
