.TH "PiP-API1-spawn" 3 "Fri Jun 10 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiP-API1-spawn \- API: Spawning PiP task
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBpip_spawn_from_main\fP"
.br
.ti -1c
.RI "\fBpip_spawn_from_func\fP"
.br
.ti -1c
.RI "\fBpip_spawn_hook\fP"
.br
.ti -1c
.RI "\fBpip_task_spawn\fP"
.br
.ti -1c
.RI "\fBpip_spawn\&.\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
