.TH "PiP-API4-query" 3 "Thu May 19 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiP-API4-query \- API: Query Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBpip_get_pipid\fP"
.br
.ti -1c
.RI "\fBpip_is_initialized\fP"
.br
.ti -1c
.RI "\fBpip_get_ntasks\fP"
.br
.ti -1c
.RI "\fBpip_get_mode\fP"
.br
.ti -1c
.RI "\fBpip_get_mode_str\fP"
.br
.ti -1c
.RI "\fBpip_get_system_id\fP"
.br
.ti -1c
.RI "\fBpip_isa_root\fP"
.br
.ti -1c
.RI "\fBpip_isa_task\fP"
.br
.ti -1c
.RI "\fBpip_is_threaded\fP"
.br
.ti -1c
.RI "\fBpip_is_shared_fd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
