.TH "pip_yield" 3 "Mon May 23 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_yield \- pip_yield
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_yield\fP (int flag)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "int pip_yield (int flag)"

.PP
\fBDescription yield\fP
.RS 4

.RE
.PP
\fBParameters\fP
.RS 4
\fIflag\fP to specify the behavior of yielding\&. Unused and reserved for BLT/ULP (in PiP-v3)
.RE
.PP
\fBReturns\fP
.RS 4
Thuis function always succeeds and returns zero\&.
.RE
.PP
\fBSee also\fP
.RS 4
sched_yield(Linux 2) 
.PP
pthread_yield(Linux 3)
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
