.TH "pip_kill_all_child_tasks" 3 "Thu May 19 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_kill_all_child_tasks \- pip_kill_all_child_tasks
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_kill_all_child_tasks\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "int pip_kill_all_child_tasks (void)"

.PP
\fBDescription\fP
.RS 4
kill all PiP tasks (excluding PiP root)
.RE
.PP
\fBNote\fP
.RS 4
This function must be called from PiP root\&.
.RE
.PP
\fBReturns\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIEPERM\fP The PiP library is not initialized yet or not called from root
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
