.TH "pip_barrier_fin" 3 "Mon May 23 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_barrier_fin \- pip_barrier_fin
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_barrier_fin\fP (pip_barrier_t *barrp)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "int pip_barrier_fin (pip_barrier_t * barrp)"

.PP
\fBDescription\fP
.RS 4
finalize barrier synchronization structure
.RE
.PP
\fBParameters\fP
.RS 4
\fIbarrp\fP pointer to a PiP barrier structure
.RE
.PP
\fBReturns\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized or already finalized 
.br
\fIEBUSY\fP there are some tasks wating for barrier synchronization
.RE
.PP
\fBSee also\fP
.RS 4
\fBpip_barrier_init\fP 
.PP
\fBpip_barrier_wait\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
