.TH "pip_get_ntasks" 3 "Fri Jun 10 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_get_ntasks \- pip_get_ntasks
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_get_ntasks\fP (int *ntasksp)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "int pip_get_ntasks (int * ntasksp)"

.PP
\fBDescription \fP
.RS 4
Obtain the maximum number of PiP tasks able to be created
.RE
.PP
\fBParameters\fP
.RS 4
\fIntasksp\fP Maximum number of PiP tasks is returned
.RE
.PP
\fBReturns\fP
.RS 4
Return 0 on success\&. Return an error code on error\&. 
.RE
.PP
\fBReturn values\fP
.RS 4
\fIEPERM\fP PiP library is not yet initialized
.RE
.PP
\fBSee also\fP
.RS 4
\fBpip_init\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
