.TH "pip_get_mode_str" 3 "Thu May 19 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_get_mode_str \- pip_get_mode_str
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBpip_get_mode_str\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "const char * pip_get_mode_str (void)"

.PP
\fBDescription\fP
.RS 4
Obtain the current PiP execution mode in character string
.RE
.PP
\fBReturns\fP
.RS 4
Return the name string of the current execution mode\&. If PiP library is not initialized yet, then this returns \fCNULL\fP\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBpip_get_mode\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
