.TH "pip_isa_root" 3 "Thu May 19 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip_isa_root \- pip_isa_root
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpip_isa_root\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "int pip_isa_root (void)"

.PP
\fBDescription\fP
.RS 4
a predicate if the calling task is the PiP root or not
.RE
.PP
\fBReturns\fP
.RS 4
Return a non-zero value if the caller is the PiP root\&. Otherwise this returns zero\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBpip_init\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
