.TH "pip-man" 1 "Mon May 23 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-man \- pip-man
.PP
 \- show a PiP man page  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBSynopsis\fP
.RS 4
pip-man [MAN-OPT] MAN-TOPIC
.RE
.PP
\fBDescription\fP
.RS 4
Show PiP man pages\&. It can also accept the man command options\&.
.RE
.PP
\fBSee also\fP
.RS 4
man(1)
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
