.TH "pip-check" 1 "Fri Jun 10 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pip-check \- pip-check
.PP
 \- checking if a progarm can run sa a PiP root and/or PiP task  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBSynopsis\fP
.RS 4
pip-check [ OPTION ] PIP-PROG [\&.\&.\&.]
.RE
.PP
\fBParameters\fP
.RS 4
\fI-r\fP check if a\&.out can be PiP root 
.br
\fI-t\fP check if a\&.out can be PiP task 
.br
\fI-b\fP check if a\&.out can be PiP root and/or PiP task (default) 
.br
\fI-v\fP show reason 
.br
\fI-h\fP show this message
.RE
.PP
\fBSee also\fP
.RS 4
\fBpipcc\fP 
.PP
\fBpipfc\fP
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
