.TH "printpipmode" 1 "Fri Jun 10 2022" "Version 2.4.1" "Process-in-Process" \" -*- nroff -*-
.ad l
.nh
.SH NAME
printpipmode \- printpipmode
.PP
 \- print current PiP mode  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBSynopsis\fP
.RS 4
printpipmode
.RE
.PP
\fBSee also\fP
.RS 4
pip-mode
.RE
.PP
\fBAuthor\fP
.RS 4
Atsushi Hori 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Process-in-Process from the source code\&.
